Repository grafana/sentry-datasource, pull requests merged in 2023-09, with the labels that each got.

#71 Add Docker image builds and post `docker pull` commands for local testing
  .github/workflows/pull-request-image.yml
Labels: enhancement, datasource/Sentry

#72 `ConfigEditor` updates
  .config/README.md
  .config/jest.config.js
  .config/jest/utils.js
  .config/webpack/utils.ts
  .config/webpack/webpack.config.ts
  .github/workflows/detect-breaking-changes.yml
  .github/workflows/pull-request-image.yml
  .nvmrc
  cypress/integration/00_utils.ts
  cypress/integration/01_config_editor.spec.ts
  cypress/integration/02_variable_editor.spec.ts
  cypress/tsconfig.json
  package.json
  src/components/config-editor/AdditionalSettings.tsx
  src/components/config-editor/Divider.tsx
  src/editors/SentryConfigEditor.test.tsx
  src/editors/SentryConfigEditor.tsx
  src/plugin.json
  src/utils/version.test.ts
  src/utils/version.ts
  yarn.lock
Labels: effort/small

#74 Find and replace existing comment when creating a PR build
  .github/workflows/pull-request-image.yml
Labels: datasource/Sentry, effort/small

#75 Update query editor
  src/components/query-editor/IssuesEditor.spec.tsx
  src/components/query-editor/IssuesEditor.tsx
  src/components/query-editor/QueryPreview.spec.tsx
  src/components/query-editor/QueryPreview.tsx
  src/components/query-editor/QueryTypePicker.tsx
  src/components/query-editor/ScopePicker.tsx
  src/components/query-editor/StatsV2Editor.spec.tsx
  src/components/query-editor/StatsV2Editor.tsx
  src/editors/SentryQueryEditor.tsx
  src/selectors.ts
Labels: effort/small
